
name: Search_Main

on:
  schedule:
   - cron : '0 23,0-17 * * *'
 

  workflow_dispatch:

jobs:
  Search:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.6'

      - run: pip3 install -r requirements.txt
      
      - run: python main.py
