
name: Search_Main

on:
  schedule:
   - cron : '01 13-17,0 * * *'
 

  workflow_dispatch:

jobs:
  Search:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.6'

      - run: pip3 install -r requirements.txt
      
      - env:
          ID: ${{ secrets.ID }}
          PW: ${{ secrets.PW }}
          TOKEN_1: ${{ secrets.TOKEN_1 }}
          TOKEN_2: ${{ secrets.TOKEN_2 }}
          TOKEN_3: ${{ secrets.TOKEN_3 }}
        run: python main.py
